<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BoatApp.Data\BoatApp.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Operations\Setting\Dtos\" />
  </ItemGroup>

</Project>
